import type { NextPage } from "next";
import Head from "next/head";

import { useEffect, useState } from "react";

import styles from "../styles/Home.module.css";

import { Text, Box } from "@chakra-ui/layout";
import { Button } from "@chakra-ui/react";
import { Center } from "@chakra-ui/react";

const Home: NextPage = () => {
  const [loading, setLoading] = useState(true);
  const [kanyeQuote, setKanyeQuote] = useState("");
  const [quoter, setQuoter] = useState(false);

  useEffect(() => {
    fetch("https://api.kanye.rest/")
      .then((res) => res.json())
      .then((data) => setKanyeQuote(data.quote))
      .then(() => setLoading(false));
  }, [quoter]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Kanye&apos;s Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {kanyeQuote && (
          <Box p="5" shadow="md" m="2" borderWidth="1px" w="720px">
            <Center>
              <Text align="center" fontSize="2xl">{kanyeQuote}</Text>
            </Center>
            <Center>
              <Button
                mt={4}
                onClick={() => setQuoter(!quoter)}
                colorScheme="yellow"
              >
                Another
              </Button>
            </Center>
          </Box>
        )}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://basedcode.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️ in CCS{" "}
        </a>
      </footer>
    </div>
  );
};

export default Home;
