import type { NextPage } from "next";
import Head from "next/head";
import NextImage from "next/image";

import styles from "../styles/Home.module.css";

import { Stack } from "@chakra-ui/layout";
import { Checkbox } from "@chakra-ui/checkbox";

import Feature from "../components/Feature";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="basedcode" target="_blank">
            THE FUTURE OF THE WEB!
          </a>
        </h1>

        <Feature mt={8} title="Principal" desc="Buying things out"></Feature>
        <Feature title="Secondary" desc="Buying things out"></Feature>
        <Feature mb={8} title="Third" desc="Buying things out"></Feature>

        <Stack spacing={10} direction="row">
          <Checkbox colorScheme="red" defaultIsChecked>
            Checkbox
          </Checkbox>
          <Checkbox colorScheme="green" defaultIsChecked>
            Checkbox
          </Checkbox>
        </Stack>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <NextImage
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
